language: node_js
node_js:
  - "10.16"

cache:
  directories:
  - node_modules

install:
  - npm install

before_script:
  - touch .env

script:
  - make test

deploy:
  provider: script
  skip_cleanup: true
  script: make ropsten
  on:
    branch: master
    tags: true
